//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.Abiquo.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.Abiquo.Client.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting AbiquoClient instance of version &apos;{0}&apos; FAILED.
        /// </summary>
        internal static string AbiquoClientFactoryGetByVersionConnectionFailed {
            get {
                return ResourceManager.GetString("AbiquoClientFactoryGetByVersionConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting AbiquoClient instance of version &apos;{0}&apos; [AbiquoVersion: &apos;{1}&apos;] SUCCEEDED.
        /// </summary>
        internal static string AbiquoClientFactoryGetByVersionConnectionSucceeded {
            get {
                return ResourceManager.GetString("AbiquoClientFactoryGetByVersionConnectionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting AbiquoClient instance of version &apos;{0}&apos; ....
        /// </summary>
        internal static string AbiquoClientFactoryGetByVersionStart {
            get {
                return ResourceManager.GetString("AbiquoClientFactoryGetByVersionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with nick &apos;{0}&apos; does not exist in enterprise with Id = &apos;{1}&apos;.
        /// </summary>
        internal static string AbiquoClientGetUserInformationNotFound {
            get {
                return ResourceManager.GetString("AbiquoClientGetUserInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to AbiquoApiBaseUri &apos;{0}&apos; FAILED..
        /// </summary>
        internal static string AbiquoClientLoginFailed {
            get {
                return ResourceManager.GetString("AbiquoClientLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to abiquoApiBaseUri &apos;{0}&apos; ....
        /// </summary>
        internal static string AbiquoClientLoginStart {
            get {
                return ResourceManager.GetString("AbiquoClientLoginStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to AbiquoApiBaseUri &apos;{0}&apos; SUCCEEDED..
        /// </summary>
        internal static string AbiquoClientLoginSucceeded {
            get {
                return ResourceManager.GetString("AbiquoClientLoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for task completion SUCCEEDED (taskId: &apos;{0}&apos;; taskPollingWaitTimeMilliseconds: &apos;{1}&apos;, taskPollingTimeoutMilliseconds: &apos;{2}&apos;.
        /// </summary>
        internal static string AbiquoClientWaitForTaskCompletionCompleted {
            get {
                return ResourceManager.GetString("AbiquoClientWaitForTaskCompletionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for task [{0}] completion FAILED (Timeout [&apos;{1}&apos;] exceeded).
        /// </summary>
        internal static string AbiquoClientWaitForTaskCompletionExceeded {
            get {
                return ResourceManager.GetString("AbiquoClientWaitForTaskCompletionExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout exceeded while waiting for task with Id &apos;{0}&apos;.
        /// </summary>
        internal static string AbiquoClientWaitForTaskCompletionTimeout {
            get {
                return ResourceManager.GetString("AbiquoClientWaitForTaskCompletionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for task completion (taskId: &apos;{0}&apos;; taskPollingWaitTimeMilliseconds: &apos;{1}&apos;, taskPollingTimeoutMilliseconds: &apos;{2}&apos;.
        /// </summary>
        internal static string AbiquoClientWaitForTaskStart {
            get {
                return ResourceManager.GetString("AbiquoClientWaitForTaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking {0} {1} COMPLETED..
        /// </summary>
        internal static string BaseAbiquoClientInvokeCompleted {
            get {
                return ResourceManager.GetString("BaseAbiquoClientInvokeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type &apos;{0}&apos;.
        /// </summary>
        internal static string BaseAbiquoClientInvokeLinksByType {
            get {
                return ResourceManager.GetString("BaseAbiquoClientInvokeLinksByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rel &apos;{0}&apos;.
        /// </summary>
        internal static string BaseAbiquoClientInvokeRel {
            get {
                return ResourceManager.GetString("BaseAbiquoClientInvokeRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rel &apos;{0}&apos;, title &apos;{1}&apos;.
        /// </summary>
        internal static string BaseAbiquoClientInvokeRelTitle {
            get {
                return ResourceManager.GetString("BaseAbiquoClientInvokeRelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking {0} {1} ....
        /// </summary>
        internal static string BaseAbiquoClientInvokeStart {
            get {
                return ResourceManager.GetString("BaseAbiquoClientInvokeStart", resourceCulture);
            }
        }
    }
}
